version: '2'
services:
  assistantcollaborator-app:
    image: assistantcollaborator
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://assistantcollaborator-postgresql:5432/assistantCollaborator
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  assistantcollaborator-postgresql:
    extends:
      file: postgresql.yml
      service: assistantcollaborator-postgresql
